### ISSUE TITLE
Fatal error during export | Call to a member function getEmail() 

### ISSUE THREAD

**Issue by saponidas** [lepidus/fullJournalTransfer#17]
Hi, I am facing the error below  when exporting.

I have performed some cleanups in the database but the issue persists. 
I am able to export all the issues using the Native Export Plugin.

Any advice? Thanks in advance,

---------

ENVIROMENT:
OJS 3.3.0.16
Mysql 5.7
PHP 7.4

---------
Exporting journal Name..
Exporting users...
Exporting sections...
Exporting issues...
**PHP Fatal error:  Uncaught Error: Call to a member function getEmail()** on null in /var/www/html/OJS/plugins/importexport/fullJournalTransfer/filter/export/ExtendedArticleNativeXmlFilter.inc.php:153
Stack trace:
#0 /var/www/html/OJS/plugins/importexport/fullJournalTransfer/filter/export/ExtendedArticleNativeXmlFilter.inc.php(132): ExtendedArticleNativeXmlFilter->createQueryParticipantsNode()
#1 /var/www/html/OJS/plugins/importexport/fullJournalTransfer/filter/export/ExtendedArticleNativeXmlFilter.inc.php(53): ExtendedArticleNativeXmlFilter->addQueries()
#2 /var/www/html/OJS/plugins/importexport/fullJournalTransfer/filter/export/ExtendedArticleNativeXmlFilter.inc.php(35): ExtendedArticleNativeXmlFilter->addStageChildNodes()
#3 /var/www/html/OJS/plugins/importexport/fullJournalTransfer/filter/export/ExtendedArticleNativeXmlFilter.inc.php(23): ExtendedArticleNativeXmlFilter->addStages()
#4 /var/www/html/OJS/lib/pkp/plugins/importexport/native/filter/SubmissionNativeXmlFilter.inc.php(67): ExtendedArticleNativeXmlF in /var/www/html/OJS/plugins/importexport/fullJournalTransfer/filter/export/ExtendedArticleNativeXmlFilter.inc.php on line 153

**Comment by thiagolepidus** [comment]
Hi @saponidas. We’ve released a new version that fixes this error: [v2.0.15.0](https://github.com/lepidus/fullJournalTransfer/releases/tag/v2.0.15.0).

**Comment by saponidas** [comment]
Many Thanks !, I have tested the new release ([[v2.0.15.0](https://github.com/lepidus/fullJournalTransfer/releases/tag/v2.0.15.0).).) and it continues for a while. Then, suddenly it stops in the step "exporting metrics", and paints a huge XML in the terminal, finishing with the next message "Could not convert selected objects."

  ```
  <metric assoc_type="256" assoc_id="1" day="20240901" metric="1" metric_type="ojs::counter" load_id="usage_events_20240901.log" country_id="AU" region="02" city="Wollongong"/>
    <metric assoc_type="256" assoc_id="1" day="20240901" metric="1" metric_type="ojs::counter" load_id="usage_events_20240901.log" country_id="CH" region="25" city="Zurich"/>
    <metric assoc_type="256" assoc_id="1" day="20240901" metric="2" metric_type="ojs::counter" load_id="usage_events_20240901.log" country_id="CN" region="22" city="Beijing"/>
    <metric assoc_type="256" assoc_id="1" day="20240911" metric="5" metric_type="ojs::counter" load_id="usage_events_20240911.log"/>
    <metric assoc_type="256" assoc_id="1" day="20240912" metric="3" metric_type="ojs::counter" load_id="usage_events_20240912.log"/>
  </metrics>
</journal>

Could not convert selected objects.
```

I  launched the script 3-4 times, with the "-d memory_limit=-1 ".
There is enough disk, and php.ini setting are very relaxed. 
No tar.gz file is generated, neither during the process, nor after the message

Have you faced this issue before?

Thanks in advance,

**Comment by thiagolepidus** [comment]
Hi @saponidas.

This error occurs when the XML validation fails. The reason for the error is displayed at the end of the execution, but since the XML content is also displayed afterward, it becomes difficult to see the reason when the XML is extensive.

If possible, could you comment on the following [section](https://github.com/pkp/pkp-lib/blob/stable-3_3_0/classes/plugins/ImportExportPlugin.inc.php#L175) in the file ojs/lib/pkp/classes/plugins/ImportExportPlugin.inc.php and run it again so we can identify the cause of the validation failure?

Thanks in advance,

**Comment by saponidas** [comment]
Thanks for your quick reply, here is the full output after commenting the line:

```
Exporting journal Journal Name...
Exporting users...
Exporting sections...
Exporting issues...
PHP Notice:  Trying to get property 'documentElement' of non-object in /var/www/html/OJS/plugins/importexport/fullJournalTransfer/filter/export/ExtendedIssueNativeXmlFilter.inc
PHP Notice:  Trying to get property 'documentElement' of non-object in /var/www/html/OJS/plugins/importexport/fullJournalTransfer/filter/export/ExtendedIssueNativeXmlFilter.inc
Exporting articles...
Exporting metrics...
Validation errors:
Element '{http://pkp.sfu.ca}participants': Missing child element(s). Expected is ( {http://pkp.sfu.ca}participant ).
Element '{http://pkp.sfu.ca}participants': Missing child element(s). Expected is ( {http://pkp.sfu.ca}participant ).
Element '{http://pkp.sfu.ca}participants': Missing child element(s). Expected is ( {http://pkp.sfu.ca}participant ).
Invalid XML:
Could not convert selected objects.

```

Thanks in advance,

**Comment by thiagolepidus** [comment]
This error is related to an inconsistency in the database: some discussions do not have participants with valid user IDs. According to OJS business logic, all discussions must have participants.

To resolve this issue, we recommend that you correct it directly in the database by deleting these invalid discussions.

Below, you will find an SQL query that helps identify the IDs of the affected discussions:

```sql
SELECT q.query_id
FROM queries q
LEFT JOIN query_participants qp ON q.query_id = qp.query_id
LEFT JOIN users u ON qp.user_id = u.user_id
GROUP BY q.query_id
HAVING COUNT(*) = SUM(CASE WHEN u.user_id IS NULL THEN 1 ELSE 0 END);
```

**Comment by diegoabadan** [comment]
> To resolve this issue, we recommend that you correct it directly in the database by deleting these invalid discussions.

Regarding the deletion of discussions, please check beforehand that they can actually be deleted (e.g. the content may be permanently lost) and ensure that there is a previous backup.

**Comment by saponidas** [comment]
Many thanks! I was able to perform the import/export task successfully.
<br>

 NOTE 

I would recommend you to add a note in the docs. The import process sends an email notification to the imported users  "Journal Registration" (You have now been registered as user with journal name...) . This is fine, but you can be sending these emails without being aware while testing the plugin.
Eg. 
-During testing, we strongly recommend to disable the email functionality in the config.inc.php file before launching the import script. A "Journal Registration" email is sent to all the imported users. Bear in mind this also when importing on production server as well.

<br>

***
OTHER ISSUE SOLVED

I wanted to share a solution to a problem I had and was able to resolve. In general, it is good practice to first use the native XML plugin to export each issue separately. If one fails, it will most likely fail with this plugin as well. So you can solve the issues one by one.

ERROR
```
Exporting metrics...
Validation errors:
Element '{http://pkp.sfu.ca}submission_file', attribute 'stage': [facet 'enumeration'] The value '' is not an element of the set {'public', 'submission', 'note', 'review_file', 'review_attachment', 'final', 'fair_copy', 'editor', 'copyedit', 'proof', 'production_ready', 'attachment', 'query', 'review_revision', 'dependent'}.
```


This happens when there are submissions with an incorrect file_stage (in my case, 7 or 8).
**Please, take a database backup first.**
In Mysql console:

explain table:
`explain submission_files;`

find the incorrect stage 7:
`select * from submission_files where file_stage=7;`

change it to a correct stage (15)
`UPDATE submission_files SET file_stage='15' where file_stage=7;`

find the incorrect stage 8:
`select * from submission_files where file_stage=8;`

change it to a correct stage (15)
`UPDATE submission_files SET file_stage='15' where file_stage=8;`



Hope this helps others,
Best,

**Comment by diegoabadan** [comment]
We're glad you successfully completed the import/export @saponidas!

Thank you for your feedback and suggestions. We'll update the README.
