### ISSUE TITLE
OJS3 support

### ISSUE THREAD

**Issue by ajnyga** [lepidus/fullJournalTransfer#6]
Hi,

First of all thank you for the great plugin you created. It worked without any problems when I transfered two OJS2 journals last fall.

However, I would like to know if you have plans to support OJS3 in the near future?

**Comment by pablovp86** [comment]
Hi, 

Thanks ajnyga!

We don't have near future plans for this plugin. However we are planning to review this after OJS **3.1** is released.

Best Regards.

**Comment by fseduardo** [comment]
Congrats on the job!

Any expectation to support version 3.1?

**Comment by diegoabadan** [comment]
Thanks!

Not in the moment. I suggest follow:
https://github.com/pkp/pkp-lib/issues/3261

**Comment by diegoabadan** [comment]
With funding from Unifesp, we are at an advanced stage of developing the OJS 3.3 version!

**Comment by diegoabadan** [comment]
We've released a preliminary package to start testing the OJS 3.3 plugin that extends what the native article/user import and export plugins do.

Development can be followed here:
https://github.com/lepidus/fullJournalTransfer

We're going to start more intensive testing now. Soon it should be ready for use in most cases.

**Comment by diegoabadan** [comment]
We officially have the plugin for OJS 3.3!

We would like to thank the Federal University of São Paulo (Unifesp) and Federal University of Recôncavo da Bahia (UFRB) for funding this version and everyone who helped with its development!
