### ISSUE TITLE
no export tarfile produced

### ISSUE THREAD

**Issue by titaniumbones** [lepidus/fullJournalTransfer#7]
Hi there,
I'm trying to export a journal from an installation running OJS 2.4.8.3.  I am able to execute the command-line export command, e.g.:

`php tools/importExport.php FullJournalImportExportPlugin export ~/cat-export.tar.gz catalyst`

No error is triggered (I tested by trying to write to a directory I have no permissions on, and using an incorrect filepath -- those both fail and give errors). However, the tarfile is not produced. I've done a `find ~/ -name "*.tar.gz"` and I don't see the file anywhere. I imagine something is going wrong in the `handleExport` function, but I'm not familiar enough with the codebase & PHP in general to say more.  

If you have some guidance I'd be really grateful! Thank you.

**Comment by diegoabadan** [comment]
Hello titaniumbones

We never saw anything like it. What version of PHP is being used?

You can export via the command line an issue by native plugin OJS?

I'm sorry for the late reply.

**Comment by juanCure** [comment]
Hi everyone

I have the same issue, when I try to create the tar.gz file using the export action of the plugin. It's not created anything.

I have tried using the NativeImportExport tool and seems the same trouble. 

My version of PHP is 5.6.35.

**Comment by titaniumbones** [comment]
@diegoabadan I'm sorry I never got back to you. I had to abandon the migration work and someone else used another method -- I odn't know which one -- to finish the job.  

@juanCure I hope you are able to work this out.

**Comment by titaniumbones** [comment]
@diegoabadan I'm sorry I never got back to you. I had to abandon the migration work and someone else used another method -- I odn't know which one -- to finish the job.  

@juanCure I hope you are able to work this out.

**Comment by juanCure** [comment]
Thanks @titaniumbones for your response. 

@lepidus, @diegoabadan  

I have tested this plugin with an instance of OJS 2.4.6 with a single journal created, and I have got success in the process of export and import that journal in another instance of OJS 2.4.6. Here left the issue where describe that test #9.

However when I try to export a journal from OJS 2.4.6 with multiple journals is when the plugin creates nothing. I have checked my PHP log file but there isn't some error message. I have noticed  the plugin creates within of my files directory **(files_dir in config.inc.php)**, other directory called **fullJournalImportExport** and within this there is a file called **journal.xml** which is not complete, I reviewed its structure and I found that the XML file ends with the `<reviewForms></reviewForms>` tags, there is nothing about users, articles, files, etc. 

I left the last part of this journal xml file:

```
<announcement>
   <oldId>272</oldId>
   <dateExpire>2018-07-22 23:59:59</dateExpire>
   <datePosted>2018-06-28</datePosted>
   <settings>
    <setting name="description" type="string" locale="es_ES">&lt;p&gt;Comunicamos a los autores interesados en publicar en la Revista Mexicana de Ciencias Políticas y Sociales, que &lt;strong&gt;debido al periodo vacacional de la UNAM (del 1 de Julio al 22 de Julio del 2018)&lt;/strong&gt;, mantendremos cerrada temporalmente la recepción de artículos y reseñas.&lt;/p&gt;&lt;p&gt;&lt;strong&gt;A partir del 23 de julio del 2018 retomaremos las actividades normales.&lt;/strong&gt;&lt;/p&gt;&lt;p&gt;&lt;em&gt;Cabe añadir que este periodo vacacional no afectará el seguimiento de ningún proceso de dictamen que este en curso, pues no perderemos el contacto con los autores y revisores.&lt;/em&gt;&lt;/p&gt;&lt;p&gt;Muchas gracias por su comprensión.&lt;/p&gt;&lt;p&gt;El equipo editorial de la RMCPyS.&lt;/p&gt;</setting>
    <setting name="descriptionShort" type="string" locale="es_ES">&lt;p&gt;Por motivos del periodo vacacional de la UNAM (del 1 de Julio al 22 de Julio del 2018), la Revista Mexicana de Ciencias Políticas y Sociales, mantendrá cerrada temporalmente la recepción de artículos y reseñas.&lt;/p&gt;&lt;p&gt;A partir del 23 de julio del 2018 retomaremos las actividades normales.&lt;/p&gt;&lt;p&gt;Muchas gracias por su comprensión.&lt;/p&gt;&lt;p&gt;El equipo editorial de la RMCPyS.&lt;/p&gt;</setting>
    <setting name="title" type="string" locale="es_ES">AVISO IMPORTANTE: A nuestros autores interesados en publicar</setting>
   </settings>
  </announcement>
 </announcements>
 <reviewForms>
  <reviewForm>
   <oldId>136</oldId>
   <sequence>1</sequence>
   <active>1</active>
   <settings>
    <setting name="description" type="string" locale="en_US">&lt;ol&gt;&lt;li&gt;AAAAAAAAAAAAAA&lt;/li&gt;&lt;li&gt;BBBBBBBBBB&lt;/li&gt;&lt;/ol&gt;&lt;ul&gt;&lt;li&gt;CCCCCCCCCCCCC&lt;/li&gt;&lt;/ul&gt;</setting>
    <setting name="title" type="string" locale="en_US">REQUIREMENTS</setting>
   </settings>
  </reviewForm>
 </reviewForms>
```

I hope @lepidus, @diegoabadan  can help me to find a solution to this issue, thank you in advance for your help.

**Comment by diegoabadan** [comment]
Closing for the time that has passed. We're sorry we weren't able to help more.
