### ISSUE TITLE
Clarification on OJS version

### ISSUE THREAD

**Issue by kaitlinnewson** [lepidus/fullJournalTransfer#8]
Hi, I think the documentation for this plugin is a little confusing, and I was hoping for some clarification.

In one area you say "This is an import/export plugin for OJS 2.4.6, 2.4.7, 2.4.8 and 2.4.8.1 ", and then in another you say "This plugin requires OJS 2.4.6 in both OJS instances". What version does the plugin work with or require? And are there any PHP version requirements? 

I'm asking because we're currently trying to import a journal from 2.4.8.3 into an instance with 2.4.8.1, but have not been able to successfully import so far.

**Comment by diegoabadan** [comment]
Hi,

We tested from OJS 2.4.6 to 2.4.8.1. But it probably works up to 2.4.8.3.

However, the journal migration should be between two OJS instances of the same OJS version (2.4.8.1 to 2.4.8.1, 2.4.6 to 2.4.6 and so on).

We use PHP 5.5.9 successfully.
We have received reports of problems with the version of PHP, so we imagine that supports a wider range of versions of PHP successfully.

Thanks for the feedback, we will improve the documentation.

**Comment by kaitlinnewson** [comment]
Thanks for clarifying!

**Comment by diegoabadan** [comment]
Updated documentation.
